import React from "react";
import { Card, CardHeader, CardTitle, CardContent, Badge, Button } from "../components/ui/shared";
import { ShieldAlert, AlertTriangle, Fingerprint, MapPin, Search } from "lucide-react";

export function AgentRiskAlerts() {
  const alerts = [
    {
      id: "RA-901",
      session: "8892-XT",
      customer: "Arjun Mehta",
      type: "Geolocation Mismatch",
      severity: "high",
      description: "User IP resolves to Mumbai, MH but stated home address is Pune, MH (150+ km discrepancy).",
      icon: MapPin,
      time: "2 mins ago"
    },
    {
      id: "RA-902",
      session: "4421-AB",
      customer: "Priya Sharma",
      type: "Synthetic ID Probability",
      severity: "high",
      description: "PAN Card linked recently compared to stated credit history. Face match score borderlining 82% threshold.",
      icon: Fingerprint,
      time: "15 mins ago"
    },
    {
      id: "RA-903",
      session: "9910-KL",
      customer: "Rajat Gupta",
      type: "Watchlist Partial Match",
      severity: "medium",
      description: "Name matched 75% on CIBIL PEP database. Requires manual secondary document verification.",
      icon: ShieldAlert,
      time: "1 hour ago"
    }
  ];

  return (
    <div className="p-8 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <AlertTriangle className="w-6 h-6 text-amber-500" /> Risk Alerts
          </h1>
          <p className="text-slate-500 mt-1">Manage flags generated by AI fraud detection engine.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="gap-2">
            <Search className="w-4 h-4" /> Filter
          </Button>
          <Button variant="default" className="bg-amber-600 hover:bg-amber-700">
            Export Report
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Summary Card */}
        <Card className="lg:col-span-1 border-slate-200">
          <CardHeader className="bg-slate-50 border-b border-slate-100">
            <CardTitle>System Status</CardTitle>
          </CardHeader>
          <CardContent className="p-6 space-y-6">
            <div>
              <p className="text-sm font-medium text-slate-500 mb-1">Active High-Risk Alerts</p>
              <div className="text-4xl font-bold text-amber-600">2</div>
            </div>
            <div>
              <p className="text-sm font-medium text-slate-500 mb-1">AI Detection Confidence</p>
              <div className="flex items-center gap-2">
                <div className="flex-1 bg-slate-100 h-2 rounded-full overflow-hidden">
                  <div className="bg-emerald-500 w-[96%] h-full rounded-full" />
                </div>
                <span className="font-bold text-slate-900 text-sm">96%</span>
              </div>
            </div>
            <div className="pt-4 border-t border-slate-100">
              <Button className="w-full" variant="outline">Review SLA Policy</Button>
            </div>
          </CardContent>
        </Card>

        {/* Alerts List */}
        <div className="lg:col-span-2 space-y-4">
          {alerts.map((alert) => (
            <Card key={alert.id} className={`border-l-4 ${alert.severity === 'high' ? 'border-l-amber-500 border-amber-200 bg-amber-50/20' : 'border-l-blue-500 border-blue-200 bg-blue-50/20'}`}>
              <div className="p-5 flex gap-4">
                <div className={`p-3 rounded-full shrink-0 ${alert.severity === 'high' ? 'bg-amber-100 text-amber-600' : 'bg-blue-100 text-blue-600'}`}>
                  <alert.icon className="w-6 h-6" />
                </div>
                <div className="flex-1">
                  <div className="flex justify-between items-start mb-1">
                    <h3 className="font-bold text-slate-900 text-lg flex items-center gap-2">
                      {alert.type}
                      <Badge variant={alert.severity === 'high' ? 'destructive' : 'warning'} className="text-xs uppercase tracking-wider">
                        {alert.severity} Risk
                      </Badge>
                    </h3>
                    <span className="text-xs text-slate-500 font-medium">{alert.time}</span>
                  </div>
                  <div className="text-sm text-slate-600 mb-4 flex items-center gap-4">
                    <span><strong className="text-slate-900 font-medium">Session:</strong> #{alert.session}</span>
                    <span><strong className="text-slate-900 font-medium">Customer:</strong> {alert.customer}</span>
                  </div>
                  <p className="text-sm text-slate-700 bg-white p-3 rounded-lg border border-slate-200 shadow-sm">
                    {alert.description}
                  </p>
                  
                  <div className="mt-4 flex justify-end gap-3 border-t border-slate-100/50 pt-4">
                    <Button variant="ghost" size="sm" className="text-slate-500">Dismiss (False Positive)</Button>
                    <Button variant="secondary" size="sm" className="bg-slate-900 text-white hover:bg-slate-800">
                      Join Live Session
                    </Button>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
}
